/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stacks;

import Stacks.structure.Stack;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    public void pushTest() {
        Stack nodeOne = new Stack();

        nodeOne.push("Ghadeer");

        assertEquals("Stack{top=Ghadeer'}",nodeOne.toString());

    }

}
