/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Linked.list;

import Linked.list.structure.LinkedList;

public class Library {
    public static void main(String[] args) {
        System.out.println("Hello World");


        LinkedList instance1 =  new LinkedList();
        instance1.insert("d");
        instance1.print();

        

    }
}
