/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge7;

import Challenge7.structure.LinkedList;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class LibraryTest {
       @Test void insertTest(){
        LinkedList list = new LinkedList();

        list.insert("Hi");
        System.out.println(list);
        assertEquals("Hi",list.toString());

    }
}
