/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chalenge26;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void insertionSortTest1(){

        InsertionSort insertionSort = new InsertionSort();



        int[] arr = {3,5,4,2,7,1,11};
        insertionSort.insertionSort(arr);


        assertEquals("[1, 2, 3, 4, 5, 7, 11]", Arrays.toString(arr));
    }
}
