/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graphs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void addNode(){

        Graph graph = new Graph();

        graph.addNode("Ahmad");
        graph.addNode("Ghadeer");

        assertNotNull(graph.gettingNodes());
        assertEquals(2, graph.size());
    }

    @Test
    public void addEdge(){

        Graph graph = new Graph();

        graph.addNode("Mohammad");
        graph.addNode("Ghadeer");

        graph.addEdge("Mohammad", "Ghadeer");

        assertEquals("Ghadeer is connected to [Mohammad]Mohammad is connected to [Ghadeer]", graph.printGraph());
    }


    @Test
    public void neighboursTest(){

        Graph graph = new Graph();

        graph.addNode("Mohammad");
        graph.addNode("Ghadeer");
        graph.addNode("Naim");
        graph.addNode("Samar");

        graph.addEdge("Mohammad", "Ghadeer");
        graph.addEdge("Mohammad", "Naim");
        graph.addEdge("Samar", "Ghadeer");

        assertEquals("[Ghadeer, Naim]", graph.gettingNeighbours("Mohammad").toString());
        assertEquals("[Ghadeer]", graph.gettingNeighbours("Samar").toString());

    }

    @Test
    public void singleNodeEdgeTest(){

        Graph g = new Graph();

        g.addNode("Ghadeer");

        g.addEdge("Ghadeer","Ghadeer");

        assertEquals("Ghadeer is connected to [Ghadeer, Ghadeer]", g.printGraph());
    }

    @Test
    public void emptyGraphTest(){

        Graph g = new Graph();

        assertEquals(0, g.size());

        assertEquals("[]", g.gettingNodes().toString());
    }
}
