/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
//        public void quickSort(int[] arr, int left, int right){

        QuickSort quickSort = new QuickSort();
        int [] array = {3,2,7,9,5,4,8};


        quickSort.quickSort(array, 1, 5);


        System.out.println(Arrays.toString(array));

    }
}
