/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void mergeSortTest2(){

        QuickSort quickSort = new QuickSort();


        int [] array = {3,4,5,8,100,7,20,75,2};

        quickSort.quickSort(array, 0, 8);
        assertEquals("[2, 3, 4, 5, 7, 8, 20, 75, 100]", Arrays.toString(array));

    }
}
