/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void test(){

        HashTable<String, Integer> grades = new HashTable<>();

        assertTrue(grades.isEmpty());

        grades.add("Ahmad",90);
        grades.add("Rana", 95);
        grades.add("Mohammad", 80);
        grades.add("Saja", 50);


//        assertEquals(4,grades.getSize());

        assertTrue(grades.contains("Saja"));
        assertFalse(grades.contains("Ali"));


    }


    @Test
    public void repeatedWordTest(){

        HashTable<String, Integer> test = new HashTable<String, Integer>();

        String paragraph1 = "a fact is a fact";
        assertEquals("a", test.repeatedWord(paragraph1));


    }


}

