/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hashtable;

import org.checkerframework.checker.units.qual.K;

public class Library {
    public static void main(String[] args) {


        HashTable<String, Integer> grades = new HashTable<>();


        grades.add("Ahmad",90);
        grades.add("Rana", 95);
        grades.add("Mohammad", 80);
        grades.add("Saja", 50);

        System.out.println(grades.getSize());
        System.out.println(grades.getValue("Rana"));

        System.out.println(grades.getSize());
        System.out.println(grades.contains("Ali"));

        System.out.println(grades.contains("Saja"));



        String paragraph3= "My name my age my gender";
        System.out.println(grades.repeatedWord(paragraph3));


    }
}
