/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

public class App {
    public static void main(String[] args) {
        System.out.println("hi");
    }
}
