/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FizzBuzz;

public class Library {
    public static void main(String[] args) {

        BinarySearchTree<Integer> tree1 = new BinarySearchTree<>();


        FizzBuzzTree<Integer> bla = new FizzBuzzTree<>();
        tree1.add(5);
        tree1.add(3);
        tree1.add(15);
        tree1.add(25);


        System.out.println( bla.fizzBuzzTree(tree1));



    }



}
