/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stacks;

import Stacks.structure.Stack;

public class Library {
    public static void main(String[] args) {
        Stack nodeOne = new Stack();

        nodeOne.push("Ghadeer");

        System.out.println(nodeOne);
    }
}
