/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FizzBuzz;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        BinarySearchTree<Integer> tree1 = new BinarySearchTree<>();


        FizzBuzzTree<Integer> test = new FizzBuzzTree<>();
        tree1.add(5);
        tree1.add(3);
        tree1.add(15);
        tree1.add(25);

        assertEquals("BinarySearchTree{root=Node{data=buzz, left=Node{data=fizz, left=null, right=null}, right=Node{data=fizzbuzz, left=null, right=Node{data=buzz, left=null, right=null}}}}", test.fizzBuzzTree(tree1).toString());

    }
}
