/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

import challenge7.structure.LinkedList;

public class App {
    public static void main(String[] args) {
        System.out.println("TEST MAIN");


        LinkedList linkedList = new LinkedList();
        linkedList.append("G");
        linkedList.append("H");
        linkedList.append("A");


//        linkedList.include("G")

//        System.out.println(linkedList.include("G"));


//       linkedList.insertBefore("A", "DDDDDDDDDDDD");

//        linkedList.insertAfter("H", "mmmmm");



        System.out.println(linkedList.include(1));




    }
}
