/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

import challenge7.structure.LinkedList;

public class App {
    public static void main(String[] args) {
        System.out.println("TEST MAIN");


        LinkedList linkedList = new LinkedList();
        linkedList.append("G");
        linkedList.append("H");
        linkedList.append("A");
        linkedList.append("New");


        LinkedList linkedList2 = new LinkedList();
        linkedList2.append("2");
        linkedList2.append("H2");
        linkedList2.append("A2");
        linkedList2.append("2");


//        linkedList.print();
//
        linkedList.insert("Inser");
//        linkedList.print();
//
////        linkedList.include("G")
//
////        System.out.println(linkedList.include("G"));
//
//
       linkedList.insertBefore("A", "DDDDDDDDDDDD");
//       linkedList.print();
//
        linkedList.insertAfter("H", "mmmmm");


        linkedList.print();


        System.out.println(linkedList.valueFromEnd(4));
//        linkedList.print();



        linkedList.print();
        linkedList2.print();

        System.out.println(linkedList.zippedList(linkedList, linkedList2));














    }
}
