/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import trees.trees.BinarySearchTree;
import trees.trees.BinaryTreeClass;


public class Library {
    public static void main(String[] args) {
        System.out.println("hi");


        BinarySearchTree<Integer> tree = new BinarySearchTree<>();

        tree.add(30);
        tree.add(80);
        tree.add(20);
//        tree.add(90);
//        tree.add(10);
        tree.add(50);
//        tree.add(65);
        tree.add(53);


//        System.out.println(tree.breadthFirst(tree));


//        tree.findMaxvalue();

////
//        System.out.println(tree);
////
//        System.out.println(tree.contains(30));
//        System.out.println(tree.contains(5));

//
//        tree.inorderTraversal();

//        tree.postOrderTraversal();

//
//        tree.preOrderTraversal();

        BinarySearchTree<Integer> tree2 = new BinarySearchTree<>();



        tree2.add(80);
        tree2.add(20);
        tree2.add(90);

        tree2.add(50);

        tree2.add(53);

        System.out.println( tree2.breadthFirst(tree2));




    }


}
