/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graphs;

import java.util.ArrayList;
import java.util.List;

public class Library {


        public static void main(String[] args) {

            Graph graph = new Graph();

            graph.addNode("M");
            graph.addNode("Ghadeer");
            graph.addNode("Naim");
            graph.addNode("Samar");

            graph.addEdge("M","Ghadeer");
            graph.addEdge("M", "Naim");
            graph.addEdge("M", "Samar");
            graph.addEdge("Ghadeer", "Naim");
            graph.addEdge("Naim", "Samar");
            graph.addEdge("Samar", "Ghadeer");

            System.out.println(graph.printGraph());;

            System.out.println();
            System.out.println(graph.gettingNodes());

            System.out.println();
            System.out.println(graph.gettingNeighbours("Mohammad"));

            System.out.println();
            System.out.println(graph.size());





            Graph graph1 = new Graph();

            graph1.addNode("Pandora");
            graph1.addNode("Arendelle");
            graph1.addNode("Metroville");
            graph1.addNode("Monstroplolis");
            graph1.addNode("Narnia");
            graph1.addNode("Naboo");

            graph1.addEdge("Pandora", "Arendelle");
            graph1.addEdge("Arendelle", "Metroville");
            graph1.addEdge("Arendelle", "Monstroplolis");
            graph1.addEdge("Metroville", "Narnia");
            graph1.addEdge("Metroville", "Naboo");
            graph1.addEdge("Metroville", "Monstroplolis");
            graph1.addEdge("Monstroplolis", "Naboo");
            graph1.addEdge("Narnia", "Naboo");


            System.out.println(graph1.breadthTraversal( "Pandora"));

        }

  
    }
