/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Practice;

public class Library {
    public static void main(String[] args) {
//                Arrays.countCharacters("THis & * 12345678z_k ");
//        String [] arr = {"Apple", "Banana", "Cucumber", "Watermelon", "Ice-cream", "Orange", "Eggplant", "Egg"};
//        Arrays.printCustomization(arr);
//        Arrays.printNamesLongerThanFive(arr);

        int [] arr1 = {2,3,4};
        int [] arr2 = {1,3,4};

        System.out.println(Arrays.arraysIntersection(arr1, arr2));;

    }
}
