/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Practice;

import java.sql.SQLOutput;
import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
//                ArraysPractice.countCharacters("THis & * 12345678z_k ");
//        String [] arr = {"Apple", "Banana", "Cucumber", "Watermelon", "Ice-cream", "Orange", "Eggplant", "Egg"};
//        ArraysPractice.printCustomization(arr);
//        ArraysPractice.printNamesLongerThanFive(arr);
//

//        int [] arr1 = {2,3,4};
//        int [] arr2 = {1,3,4};
//        System.out.println(ArraysPractice.arraysIntersection(arr1, arr2));
//
//          int [] arr3 = {1,0,2,0,3, 4, 0, 0, 5,6,7};
//          System.out.println(Arrays.toString(ArraysPractice.moveZeros(arr3)));
//
//        int [] arr4 = {0,1,2,4};
//        System.out.println(ArraysPractice.missingNumber(arr4));



        int [] arr = {2,5,6,7,9,10,11,15};
        int k = 2;
//        System.out.println(Arrays.toString(ArraysPractice.removeElement(arr, 3)));



//        System.out.println((ArraysPractice.sumBetweenLargestAndSmallest(arr)));

//
//        System.out.println(ArraysPractice.charactersCount("Ghadeeerrkkkkt"));
//        int [] sumArr = {1, 3, 7, 2, 5, 10,2,3};
//        System.out.println(ArraysPractice.sumOfOddNumbers(sumArr));





//
//        System.out.println( ArraysPractice.indexOfRepeatedIntegerIndex(arr));


//        System.out.println((Arrays.toString(ArraysPractice.twoSum(arr, k))));
//            ArraysPractice.repeatedIntegerswith(arr);

//        System.out.println(Arrays.toString(ArraysPractice.moveZeros(arr)));
//        System.out.println(ArraysPractice.searchInsert(arr, k));


        int [] arr2 = {1,2,4,7,8};
        System.out.println(ArraysPractice.returnMissingInteger(arr2));
        System.out.println(ArraysPractice.returnMissingInteger2(arr2));



    }
}
