/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chalenge26;

public class Library {
    public static void main(String[] args) {
        InsertionSort insertionSort = new InsertionSort();


        insertionSort.insertionSort();
    }
}
