/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge3;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        System.out.println("TEST");
        int[] arr1 = new int [] {1,2,3,4,5};
        int x = 4;
        System.out.println((binarySearch(arr1, x)));;
    }

    public static int binarySearch(int[] arr, int x) {

       int returnedindex = -1;
       int maxInndex = (arr.length - 1);
       int minIndex = 0;

       while(0<= (maxInndex-minIndex)){
           int middleIndex = (maxInndex + minIndex)/2;
           if(x == arr[middleIndex]){
               returnedindex =  middleIndex;
               break;
           }else if (x < arr[middleIndex]){
               maxInndex =  middleIndex -1;

           }
           else{
               minIndex = middleIndex + 1;
           }

       }
     return returnedindex;
    }


}

