/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge6;


import challenge6.structure.LinkedList;

public class App {
    public static void main(String[] args) {
        System.out.println("TEST MAIN");


        LinkedList linkedList = new LinkedList();
        linkedList.append("G");
        linkedList.append("H");
        linkedList.append("A");


        LinkedList linkedList2 = new LinkedList();
        linkedList2.append("LLL");
        linkedList2.append("HLLLL");
        linkedList2.append("Mohammad");



//        System.out.println( LinkedList.zippedList(linkedList,linkedList2));





//
//       linkedList.insertBefore("A", "DDDDDDDDDDDD");

//        linkedList.insertAfter("H", "mmmmm");
//                linkedList.print();




    }
}
