/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import src.structure.LinkedList;

public class Main {
    public static void main(String[] args) {
        System.out.println("hello");

        LinkedList linkedList = new LinkedList();
        linkedList.add("J");
        linkedList.add("A");
        linkedList.add("S");
        linkedList.add("O");
        linkedList.add("N");



        linkedList.print();

//        System.out.println( linkedList);
    }
}
