/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stacks;

import Stacks.structure.*;

public class Library {
    public static void main(String[] args) {
//        Stack nodeOne = new Stack();

//
//
//
//
//
//        nodeOne.push("Ghadeer");
//        nodeOne.push("Gha");
//        nodeOne.push("G");


//        nodeOne.pop();
//        System.out.println(nodeOne);
//
//        System.out.println(nodeOne.peek());


//        Queues nodeTwo = new Queues();
//
//        nodeTwo.enqueue("Ghadeer");
//        nodeTwo.enqueue("Gha");
//        nodeTwo.enqueue("G");
//
//        nodeTwo.peek();


//        System.out.println(nodeTwo.peek());

//        nodeOne.pop();
//        System.out.println(nodeOne);
//
//        System.out.println(nodeOne.peek());



//
//        Brackets stack1 = new Brackets();
//
//
//        System.out.println(stack1.bracketValidation("{[]]]}"));



//        PseudoQueue queue = new PseudoQueue();

//        queue.enqueue("Ghadeer");
//        queue.enqueue("Khasawneh");


//        queue.dequeue();



//
//        System.out.println(queue);
//
//        System.out.println(queue.dequeue());


//        Stack nodeThree = new Stack();
//
//        nodeThree.push("10");
//        nodeThree.push("15");
//        nodeThree.push("20");
//        nodeThree.push("18");
////        nodeThree.getMaximum();
//
//
//        System.out.println(nodeThree.getMaximum());


        //////////////////////////////////////////////////////////////////////////////////////////////

        AnimalShelter animalShelter = new AnimalShelter();

        Animal catAnimal = new Cat("Bibi");
        Cat cat1 = new Cat("Angora");



        Animal dogAnimal = new Dog("Bla");
        Dog dog2 = new Dog("Shephered");


        animalShelter.enqueue(catAnimal);
        animalShelter.enqueue(cat1);

        animalShelter.enqueue(dogAnimal);
        animalShelter.enqueue(dog2);


//        System.out.println(animalShelter);



//        animalShelter.dequeue("cat");
//        System.out.println(animalShelter);
//
        animalShelter.dequeue("dog");



        System.out.println(animalShelter);


    }




}